### ISSUE TITLE
Adding GPU support 

### ISSUE THREAD

**Issue by carlosbravoa** [canonical/anbox-cloud-docs#193]
I would like to see in which step do I need to go to the terminal and install GPU drivers

---
*Reported from: https://documentation.ubuntu.com/anbox-cloud/en/latest/howto/install-appliance/install-on-aws/*

**Comment by morphis** [comment]
Hey @carlosbravoa!

The GPU driver installation is done as part of https://documentation.ubuntu.com/anbox-cloud/en/latest/tutorial/installing-appliance/#prepare-the-machine which is linked to at thel last step of the how-to you're referring to, see https://documentation.ubuntu.com/anbox-cloud/en/latest/howto/install-appliance/install-on-aws/#finish-the-installation

**Comment by keirthana** [comment]
Thank you for the feedback @carlosbravoa, we appreciate it.
