### ISSUE TITLE
Review juju crashdump command

### ISSUE THREAD

**Issue by lathiat** [canonical/anbox-cloud-docs#206]
While trying to use juju-crashdump, I found the following

1. With juju 3.5.x, you seem to need to use `juju-crashdump` rather than `juju crashdump`, it seems the plugin support was maybe dropped or is broken. The juju-crashdump docs don't currently reflect this.
2. With the command given, it says that as_root is needed, so perhaps we need to add --as-root to the command?
    `2024-11-05 06:32:56,790 - The as_root flag must be used to run addon debug-layer`

---
Document: howto/troubleshoot/landing.md

**Comment by adglkh** [comment]
Thanks for the report.
Fixed it in the following PR
https://github.com/canonical/anbox-cloud-docs/pull/218
