### ISSUE TITLE
docs: it makes confusing 

### ISSUE THREAD

**Issue by PiCoPress** [canonical/anbox-cloud-docs#216]
*Please describe the question or issue you're facing with "GPUs and instances - Anbox Cloud documentation".*

It has an inconsistent description below screenshot.

![chrome_screenshot_2024  11  13  오전 9시 38분 30초 GMT+09_00](https://github.com/user-attachments/assets/3b278966-166c-45be-833d-4410a252c1d5)

---
*Reported from: https://documentation.ubuntu.com/anbox-cloud/en/latest/explanation/gpus-instances/*

**Comment by keirthana** [comment]
@PiCoPress Thank you for your feedback. Could you help me understand which part you find inconsistent?

**Comment by PiCoPress** [comment]
The first paragraph;
> ... However, you can enable software rendering ... with the `--enable-graphics` flag ...

But according to the last paragraph,
> If you want to let an application use the GPU ... launch it with the `--enable-graphics` flag ...
